FROM centos/python-38-centos7:latest
#FROM nvidia/cuda:11.3.1-runtime-centos7

LABEL maintainer "Z0003864<vivek.thota@zf.com>"

# Set ZF proxies
ENV http_proxy=http://frd-proxy.emea.zf-world.com:8080 \
    https_proxy=http://frd-proxy.emea.zf-world.com:8080 \
    no_proxy=.zf-world.com \
    HTTP_PROXY=http://frd-proxy.emea.zf-world.com:8080 \
    HTTPS_PROXY=http://frd-proxy.emea.zf-world.com:8080 \
    NO_PROXY=.zf-world.com

USER root

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts

USER 1001

LABEL io.k8s.description="S2I builder for custom Jupyter notebooks." \
      io.k8s.display-name="Jupyter Notebook" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,jupyter" \
      io.openshift.s2i.scripts-url="image:///opt/app-root/builder"

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
